version: 2.1

orbs:
  python: circleci/python@2.1.1

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test-python:
    # You can specify an image from Dockerhub or use one of the convenience images from CircleCI's Developer Hub
    # A list of available CircleCI Docker convenience images are available here: https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - run:
          name: Versions
          command: |
            python --version
            poetry --version
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            poetry run pytest
      - run:
          name: Run linter and formatter
          command: |
            poetry run ruff check
            poetry run ruff format
      - run:
          name: Build package
          command: |
            poetry build

  test-js:
    docker:
      - image: cimg/node:20.14
    steps:
      - checkout
      - run: node --version
      - run:
          command: |
            cd ts
            yarn
      - run:
          command: |
            cd ts
            NODE_OPTIONS=--openssl-legacy-provider yarn webpack
      - run:
          command: |
            cd ts
            yarn run format:check
            yarn run knip
            yarn run tsc --noEmit
            yarn run lint

workflows:
  main:
    jobs:
      - test-python
      - test-js
