version: 2.1

orbs:
  python: circleci/python@2.1.1

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test-python:
    # You can specify an image from Dockerhub or use one of the convenience images from CircleCI's Developer Hub
    # A list of available CircleCI Docker convenience images are available here: https://circleci.com/developer/images/image/cimg/python
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - versions:
          name: Versions
            python --version
            poetry --version
      - python/install-packages:
          pkg-manager: poetry
      - tests:
          name: Run tests
          command: |
            poetry run pytest
      - lint:
          name: Run linter and formatter
          command: |
            poetry run ruff check
            poetry run ruff format

  test-js:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - checkout
      - run: node --version
      - run:
          command: |
            cd ts
            yarn
      - run:
          command: |
            cd ts
            NODE_OPTIONS=--openssl-legacy-provider yarn webpack

workflows:
  main:
    jobs:
      - test-python
      - test-js
